services:
  api:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 movie_proj.wsgi:application
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - .:/src
      - static_volume:/src/staticfiles
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    ports:
      - "5454:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./blog-frontend
      dockerfile: Dockerfile
      args:
        - VITE_OMDB_API_KEY=${VITE_OMDB_API_KEY}
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
    # env_file:
    #   - .env
    depends_on:
      - api

volumes:
  static_volume:
  postgres_data:
