# Generated by Django 5.1.4 on 2025-03-10 13:34

import user_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_app.models.CustomUserManager()),
            ],
        ),
    ]
